server:
    port: 8081
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:postgresql://localhost:5432/user_service_db
        username: root
        password: root
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: none
        show-sql: false
management:
    endpoints:
        web:
            exposure:
                include:
                    - '*'
                
    endpoint:
        health:
            show-details: ALWAYS 

greeting: "hello user greeting service!!!!!"