server:
    port: 8081
spring:
    application:
        name: greeting-service-tow
management:
    endpoints:
        web:
            exposure:
                include:
                    - '*'
                
    endpoint:
        health:
            show-details: ALWAYS 

greeting: "hello world greeting service tow!!!!!"