server:
    port: 8080
spring:
    application:
        name: user-service-dev
    datasource:
        url: jdbc:postgresql://database:5433/user_service_db
        username: root
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: none
            show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
management:
    endpoints:
        web:
            exposure:
                include:
                    - '*'
                
    endpoint:
        health:
            show-details: ALWAYS 

    

greeting: "hello world greeting service!!!!!"